# PlatformIO Project Configuration Override — D1 Mini Joachim
# ------------------------------------------------------------------------------
# Backup original : platformio_override.ini.bak
# Cible : ESP8266 D1 Mini (nodemcuv2 — 4MB flash)
# Usermods custom : wled_weather, wled_oled, wled_buttons
# ------------------------------------------------------------------------------

[platformio]
default_envs = nodemcuv2

[env:nodemcuv2]
lib_deps =
    ${esp8266.lib_deps}
    olikraus/U8g2 @ ~2.35.19
    adafruit/Adafruit AHTX0 @ ^2.0.5
    adafruit/Adafruit BMP280 Library @ ^2.6.8
    adafruit/Adafruit BusIO @ ^1.16.2

custom_usermods =
    wled_weather
    wled_oled
    wled_buttons

build_flags = ${common.build_flags} ${esp8266.build_flags} -D WLED_RELEASE_NAME=\"ESP8266\" -D WLED_DISABLE_PARTICLESYSTEM2D -D WLED_DISABLE_ALEXA